[versions]
#jetbrains
kotlin = "2.3.0"
#KSP
ksp = "2.3.4"
#Detekt
detekt = "1.23.8"
detektCompose = "0.4.28"
#Room
room = "2.8.4"
#Fossify
commons = "5.13.1"
#Gradle
gradlePlugins-agp = "8.11.1"
#Compose
compose-bom = "2025.01.00"
compose-activity = "1.10.0"
#LiquidGlass
backdrop = "2.0.0-alpha01"
shapes = "1.0.4"
#Coil
coil = "2.6.0"
#Serialization
kotlinx-serialization = "1.7.3"
#build
app-build-compileSDKVersion = "36"
app-build-targetSDK = "36"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
[libraries]
#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
#LiquidGlass
backdrop = { module = "io.github.kyant0:backdrop", version.ref = "backdrop" }
shapes = { module = "io.github.kyant0:shapes", version.ref = "shapes" }
#Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
#Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]
compose = [
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling-preview",
    "compose-material3",
    "compose-foundation",
    "compose-activity",
]
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
